name: format_date
description: "To be able to format dates easily. You just need to provide a datetime object and a desire formatting as String, as input to one of the two functions - formatDate or formatTime, to get desired output."
version: 0.0.4
repository: https://github.com/gru786/format_date.git
 

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  